export interface QuoteSeed {
  text: string;
  author: string;
}

export const DEFAULT_QUOTES: QuoteSeed[] = [
  { text: 'Stay hungry stay foolish', author: 'Steve Jobs' },
  { text: 'Simplicity is the ultimate sophistication', author: 'Leonardo da Vinci' },
  { text: 'Fortune favors the bold', author: 'Virgil' },
  { text: 'Make it work then make it right', author: 'Kent Beck' },
  { text: 'Creativity takes courage', author: 'Henri Matisse' },
  { text: 'The future depends on what you do today', author: 'Mahatma Gandhi' },
  { text: 'Action is the foundational key to all success', author: 'Pablo Picasso' },
  { text: 'Well begun is half done', author: 'Aristotle' },
  { text: 'Ideas are easy execution is everything', author: 'John Doerr' },
  { text: 'Done is better than perfect', author: 'Sheryl Sandberg' },
  { text: 'Make each day your masterpiece', author: 'John Wooden' },
  { text: 'Wherever you go go with all your heart', author: 'Confucius' },
  { text: 'What we think we become', author: 'Buddha' },
  { text: 'The details are not the details they make the design', author: 'Charles Eames' },
  { text: 'Quality means doing it right when no one is looking', author: 'Henry Ford' },
  { text: 'Build what matters', author: 'Stewart Butterfield' },
  { text: 'You miss one hundred percent of the shots you do not take', author: 'Wayne Gretzky' },
  { text: 'The best way out is always through', author: 'Robert Frost' },
  { text: 'Nothing will work unless you do', author: 'Maya Angelou' },
  { text: 'If it is not a hell yes it is a no', author: 'Derek Sivers' },
  { text: 'Great things are done by a series of small things brought together', author: 'Vincent van Gogh' },
  { text: 'Discipline is remembering what you want', author: 'David Campbell' },
  { text: 'Move fast with clear intent', author: 'Flipflap' },
  { text: 'The obstacle is the way', author: 'Marcus Aurelius' },
  { text: 'All progress takes place outside the comfort zone', author: 'Michael John Bobak' },
  { text: 'The secret of getting ahead is getting started', author: 'Mark Twain' },
  { text: 'Dreams do not work unless you do', author: 'John C Maxwell' },
  { text: 'The quieter you become the more you can hear', author: 'Ram Dass' },
  { text: 'Keep going be all in', author: 'Bryan Hutchinson' },
  { text: 'Chance favors the prepared mind', author: 'Louis Pasteur' },
  { text: 'Everything is hard before it is easy', author: 'Goethe' },
  { text: 'Do less but better', author: 'Dieter Rams' },
  { text: 'Think boldly build calmly', author: 'Flipflap' },
  { text: 'The magic is in the work', author: 'Unknown' },
  { text: 'Make visible what without you might perhaps never have been seen', author: 'Robert Bresson' },
  { text: 'Focus is saying no', author: 'Steve Jobs' },
  { text: 'If you can dream it you can do it', author: 'Walt Disney' },
  { text: 'Energy and persistence conquer all things', author: 'Benjamin Franklin' },
  { text: 'The way to get started is to quit talking and begin doing', author: 'Walt Disney' },
  { text: 'We shape our tools and thereafter our tools shape us', author: 'Marshall McLuhan' },
  { text: 'Excellence is to do a common thing in an uncommon way', author: 'Booker T Washington' },
  { text: 'What is now proved was once only imagined', author: 'William Blake' },
  { text: 'Make space for what matters', author: 'Flipflap' },
  { text: 'The only limit to our realization of tomorrow is our doubts of today', author: 'Franklin Roosevelt' },
  { text: 'The best revenge is massive success', author: 'Frank Sinatra' },
  { text: 'Look closely and think slowly', author: 'Flipflap' },
  { text: 'Light tomorrow with today', author: 'Elizabeth Barrett Browning' },
  { text: 'The harder you work the luckier you get', author: 'Gary Player' },
  { text: 'Perfection is achieved not when there is nothing more to add but when there is nothing left to take away', author: 'Antoine de Saint Exupery' },
  { text: 'The art of simplicity is a puzzle of complexity', author: 'Douglas Horton' },
  { text: 'Turn noise into rhythm', author: 'Flipflap' },
  { text: 'Without hustle talent will only carry you so far', author: 'Gary Vaynerchuk' },
  { text: 'Start where you are use what you have do what you can', author: 'Arthur Ashe' },
  { text: 'A smooth sea never made a skilled sailor', author: 'Franklin Roosevelt' }
];
